### ISSUE TITLE
Cannot Start Siri Proxy

### ISSUE THREAD

**Issue by ryanschulz** [plamoni/SiriProxy#147]
Hello, I installed every, and followed his instructions posted on the main repo. 

When I did "rvmsudo siriproxy server", nothing happened, and after a while I decided to try again in the main folder of terminal. I am new to mac so sorry.

This is the response I get.

Ryan-Schulzs-Mac-Pro:~ RyanSchulz$ rvmsudo siriproxy server
Starting SiriProxy on port 443..
/Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy.rb:26:in `rescue in block in initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy.rb:17:in`block in initialize'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy.rb:16:in`initialize'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:96:in`start_server'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:37:in`initialize'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/bin/siriproxy:6:in `new'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/bin/siriproxy:6:in`<top (required)>'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in `load'
    from /Users/RyanSchulz/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in`<main>'

Thanks,

Prior to getting everything set up, I made my FakeCa following plamoni's video on youtube, and the one the terminal code gave me was 90K and my iPhone did not accept it, unlike the 3.9K one i made prior.

**Comment by ryanschulz** [comment]
Alright, i restarted my Mac and got the server to run.

after I type "rvmsudo siriproxy server" and enter my password, it just pauses. Then I test it on my iPhone, and it says "Sorry, I do not understand "Test Siri proxy"" What is causing that?
