### ISSUE TITLE
Undefined Method on [Info - iPhone] Received Object: GetAnchors

### ISSUE THREAD

**Issue by Torsten85** [plamoni/SiriProxy#150]
Hi there,
I sometimes get this error:

```
[Info - iPhone] Received Object: CancelRequest
[Info - iPhone] Received Object: RollbackRequest
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: GetAnchors
/Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/connection.rb:99:in `has_next_object?': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/connection.rb:84:in `process_compressed_data'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/connection.rb:58:in `receive_binary_data'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy.rb:16:in `initialize'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:96:in `start_server'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:37:in `initialize'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/bin/siriproxy:6:in `new'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/bin/siriproxy:6:in `<top (required)>'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in `load'
    from /Users/mediacenter/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in `<main>'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
```

**Comment by plamoni** [comment]
I've seen this too. 

There are 3 known "types" of packets that get passed by Siri/Guzzoni. They each start with a header whose first byte is 02 (an object), 03 (a ping), or 04 (a pong). I keep wondering whether there's a "01" type of packet. I've added some code in the dev branch that catches unknown types, outputs the hex, and requests you share it with the class. I'm going to leave this issue open in hopes someone comes up with some data for us. :-)

**Comment by kevmuko** [comment]
I think the issue with the Received Object: CommandFailed occurs when sharing Location Services? At least that's what occurs on my iPhone 4.
