### ISSUE TITLE
Installed but not working

### ISSUE THREAD

**Issue by barrettj** [plamoni/SiriProxy#201]
I think I have everything installed correctly - but when I I attempt to activate siri on my phone, it gives an unavailable message and this is output on my mac:

```
/Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:714:in `connect_server': unable to resolve server address (EventMachine::ConnectionError)
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:714:in `bind_connect'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:692:in `connect'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection/iphone.rb:20:in `ssl_handshake_completed'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in `initialize'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `start_server'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in `initialize'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `new'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `<top (required)>'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `load'
    from /Users/barrettjacobsen/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `<main>'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
```

Any ideas what could cause this?

**Comment by barrettj** [comment]
Fixed.

I had attempted to take the easy way out and have my DHCP server give out the new DNS server.  Of course my iMac gets it's ip from a DHCP reservation so it was picking up itself as the DNS server and was referring to itself so it was never connecting to the actual Apple server.

I removed the entry in DHCP and manually added the DNS entry to my phone and all is working.

**Comment by iPodHacks142** [comment]
How do i do that?
