### ISSUE TITLE
Siriproxy bundle problem?

### ISSUE THREAD

**Issue by ishaper** [plamoni/SiriProxy#277]
Hi guys,

everything went ok with installing siriproxy but at the end when typing siriproxy bundle I get this error:

apple:SiriProxy pepynhoff$ siriproxy bundle
/Users/pepynhoff/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:154:in `parse': (/Users/pepynhoff/.siriproxy/config.yml): couldn't parse YAML at line 12 column 2 (Psych::SyntaxError)

```
from /Users/pepynhoff/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:154:in `parse_stream'
from /Users/pepynhoff/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:125:in `parse'
from /Users/pepynhoff/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:112:in `load'
from /Users/pepynhoff/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:229:in `load_file'
from /Users/pepynhoff/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:143:in `parse_options'
from /Users/pepynhoff/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:33:in `initialize'
from /Users/pepynhoff/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/bin/siriproxy:6:in `new'
from /Users/pepynhoff/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/bin/siriproxy:6:in `<top (required)>'
from /Users/pepynhoff/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in `load'
from /Users/pepynhoff/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in `<main>'
```

I also tried to do the same in the main folder, but this didn't helped anything.

Could someone tell me what to do?

Thank you!

**Comment by ishaper** [comment]
I deleted the Twitter and facebook code and it works?
