### ISSUE TITLE
SiriProxy is starting - but it doesn't work for me

### ISSUE THREAD

**Issue by mrJakez** [plamoni/SiriProxy#314]
Hi,

SiriProxy doesn't work on my configuration:

I'm using OSX Snow Leopard and this tutorial:
https://gist.github.com/1558903

Do you have an idea what's going wrong (please look at the attached shell-output)?

greetings
Dennis
# Steps to reproduce:
1. Start SiriProxy (rvmsudo siriproxy server)
2. Generate a siri request with an iPhone 4s -> this try will be quit with an error on the iPhone ("not possible at this time - try again later")
3. Quit the SiriProxy process.
# Complete shell output:

```
mce:SiriProxy jakez$ rvmsudo siriproxy server -l 9000 
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000100c66c80 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000100c66af0>, @zip_stream=#<Zlib::Deflate:0x00000100c66ac8>, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000100a221b8 @manager=#<SiriProxy::PluginManager:0x00000100c66618 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000100a22078 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000100a29f08>, @zip_stream=#<Zlib::Deflate:0x00000100a29ee0>, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000100a29490 @manager=#<SiriProxy::PluginManager:0x00000100a29aa8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000100a292b0 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000100a28e28>, @zip_stream=#<Zlib::Deflate:0x00000100a28d60>, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000100aa0d88 @manager=#<SiriProxy::PluginManager:0x00000100a27b68 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000100aa0c20 @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000100aa0a90>, @zip_stream=#<Zlib::Deflate:0x00000100aa0a68>, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000100a9ff28 @manager=#<SiriProxy::PluginManager:0x00000100aa0590 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000100a9fdc0 @signature=7, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000100a9fc58>, @zip_stream=#<Zlib::Deflate:0x00000100a9fc30>, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000100a9f1e0 @manager=#<SiriProxy::PluginManager:0x00000100a9f7a8 @plugins=[...]>>]
^C/Users/jakez/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine': Interrupt
    from /Users/jakez/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /Users/jakez/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in `initialize'
    from /Users/jakez/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/jakez/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `start_server'
    from /Users/jakez/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/jakez/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in `initialize'
    from /Users/jakez/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `new'
    from /Users/jakez/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `<top (required)>'
    from /Users/jakez/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `load'
    from /Users/jakez/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `<main>'
```

**Comment by vipal** [comment]
I'm getting the same thing on Ubuntu 11.10 server

**Comment by iPodHacks142** [comment]
Same here... PLEASE HELP!

**Comment by jontingvold** [comment]
I have the same problem. Has someone found a solution for it?
