### ISSUE TITLE
Failed to build native extensions

### ISSUE THREAD

**Issue by babylon558** [plamoni/SiriProxy#332]
When I run "rake install" it keeps throwing an error, "ERROR: Failed to build gem native extension."
The full output is below

Building native extensions.  This could take a while...
ERROR:  Error installing /home/siriproxy/SiriProxy/pkg/siriproxy-0.3.0.gem:
    ERROR: Failed to build gem native extension.

```
    /home/siriproxy/.rvm/rubies/ruby-1.9.3-p125/bin/ruby extconf.rb
```

checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for rb_thread_check_ints()... yes
checking for rb_time_new()... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
creating Makefile

make
compiling cplusplus.cpp
make: g++: Command not found
make: **\* [cplusplus.o] Error 127

Gem files will remain installed in /home/siriproxy/.rvm/gems/ruby-1.9.3-p125@SiriProxy/gems/eventmachine-0.12.10 for inspection.
Results logged to /home/siriproxy/.rvm/gems/ruby-1.9.3-p125@SiriProxy/gems/eventmachine-0.12.10/ext/gem_make.out

**Comment by moritzpeuser** [comment]
I'm experiencing a similar problem. `Rake install` fails at my setup with:

```
siriproxy 0.3.2 built to pkg/siriproxy-0.3.2.gem
rake aborted!
Couldn't install gem, run `gem install /home/pi/SiriProxy/pkg/siriproxy-0.3.2.gem' for more detailed output
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/bundler-1.2.3/lib/bundler/gem_helper.rb:68:in `install_gem'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/bundler-1.2.3/lib/bundler/gem_helper.rb:43:in `block in install'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/ruby_noexec_wrapper:14:in `eval'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => install
(See full trace by running task with --trace)
```

When I try to execute `gem install /home/pi/SiriProxy/pkg/siriproxy-0.3.2.gem` it returns:

```
Fetching: CFPropertyList-2.2.0.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/cache/CFPropertyList-2.2.0.gem
```

Running `rake install --trace` returns the following:

```
** Invoke install (first_time)
** Execute install
siriproxy 0.3.2 built to pkg/siriproxy-0.3.2.gem
rake aborted!
Couldn't install gem, run `gem install /home/pi/SiriProxy/pkg/siriproxy-0.3.2.gem' for more detailed output
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/bundler-1.2.3/lib/bundler/gem_helper.rb:68:in `install_gem'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/bundler-1.2.3/lib/bundler/gem_helper.rb:43:in `block in install'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/task.rb:228:in `call'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/task.rb:228:in `block in execute'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/task.rb:223:in `each'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/home/pi/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/application.rb:143:in `invoke_task'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/application.rb:101:in `each'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/application.rb:110:in `run_with_threads'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/application.rb:73:in `block in run'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/application.rb:160:in    `standard_exception_handling'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/lib/rake/application.rb:70:in `run'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/rake:19:in `load'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/rake:19:in `<main>'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/ruby_noexec_wrapper:14:in `eval'
/home/pi/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => install
```

Edit: I found out what caused the errors: There were incorrect permissions set. Execute the following command to correct them:

`sudo chown -R [username] ~/.rvm`
