### ISSUE TITLE
siriproxy attempts to write into the installed gem directory

### ISSUE THREAD

**Issue by drbrain** [plamoni/SiriProxy#333]
When running `siriproxy bundle`, siriproxy is attempting to write into the gem directory:

```
/usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/definition.rb:246:in `initialize': Permission denied - /usr/local/lib/ruby/gems/1.9.1/gems/siriproxy-0.3.0/Gemfile.lock (Errno::EACCES)
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/definition.rb:246:in `open'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/definition.rb:246:in `lock'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/environment.rb:39:in `lock'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/installer.rb:59:in `run'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/installer.rb:12:in `install'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/cli.rb:220:in `install'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendor/thor/task.rb:22:in `run'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendor/thor.rb:263:in `dispatch'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/vendor/thor/base.rb:386:in `start'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/bin/bundle:13:in `<top (required)>'
    from /usr/local/bin/bundle:19:in `load'
    from /usr/local/bin/bundle:19:in `<main>'
```

Instead, siriproxy should be installing its gems to a directory it can write to, such as ~/.siriproxy

**Comment by drbrain** [comment]
Using `BUNDLE_GEMFILE=~/.siriproxy/Gemfile siriproxy bundle install` and `BUNDLE_GEMFILE=~/.siriproxy/Gemfile sudo siriproxy server` with a hand-built Gemfile works around this issue, but building the Gemfile requires too much knowledge of ruby for most users.
