### ISSUE TITLE
Problem with mysql?

### ISSUE THREAD

**Issue by pmvieira** [plamoni/SiriProxy#384]
Hi,

Thanks for the great jobs. I'm having a problem tough... When I try to run ruby ./run.rb I get this error:

/usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mysql (LoadError)
        from /usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from /var/www/mailadmin/lib/connection.rb:3:in `<top (required)>'
        from /var/www/mailadmin/lib/mailadmin.rb:6:in`require_relative'
        from /var/www/mailadmin/lib/mailadmin.rb:6:in `<top (required)>'
        from ./run.rb:5:in`require_relative'
        from ./run.rb:5:in `<main>'

PS- Running Ubunto 12.10

Can you help me with this please?

Thanks!

**Comment by pmvieira** [comment]
Oppps! sorry! wrong github, too many open tabs!
