### ISSUE TITLE
SiriProxy with iPad 3

### ISSUE THREAD

**Issue by jamesabruce** [plamoni/SiriProxy#440]
Are there some settings somewhere that I need to change to have this working with my iPad3? I assumed it would work, since It has Siri, legitimately. running 6.1; debug output of SiriProxy as soon as button is pressed:

<code>
rvmsudo siriproxy server -l 4
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.Password:
Starting SiriProxy on 0.0.0.0:443..
SiriProxy up and running.
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fc265096b70 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fc2650969e0>, @zip_stream=#Zlib::Deflate:0x007fc2650969b8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fc263593738 @manager=#<SiriProxy::PluginManager:0x007fc265096580 @plugins=[...]>>]
[Info - iPhone] SSL completed for iPhone
[Header - iPhone] ACE /ace HTTP/1.0
[Header - iPhone] Host: guzzoni.apple.com
[Header - iPhone] Content-Length: 2000000000
[Header - iPhone] User-Agent: Assistant(iPad/iPad3,3; iPhone OS/6.1/10B141) Ace/2.1
[Header - iPhone] Accept-Language: en-US
[Header - iPhone] X-Ace-Host: stp7:36d6d9d6-d20a-4b1a-88bb-f77d4ce1e8c0
[Header - iPhone] 
[Debug - iPhone] Found end of headers
[Info - iPhone] Received Object: LoadAssistant (group: com.apple.ace.system, ref_id: , ace_id: 31FCFE53-4596-4057-8417-15139C204455)
{"class"=>"LoadAssistant",
 "aceId"=>"31FCFE53-4596-4057-8417-15139C204455",
 "group"=>"com.apple.ace.system",
 "properties"=>
  {"activationToken"=>" \xEF\x8A|\x15_ q\x8Dx\xCB\x98\xACh\x06i\xCB\xB1O?",
   "speechId"=>"02c7f1b5-d8b9-4c16-9782-b419a56c1408",
   "assistantId"=>"13f93ee0-0ca9-4034-a755-f030c69f3675",
   "sessionValidationData"=>
    "\x02\xBD\xF1iH\xC9\x13-?\xEC%~P\xCA:\xE9\x9A\x81\x19\xAD\x17\x9F\x8F1\x15tc;u\x02>{\xE7\x00\x00\x02\x00\x06\x00\x00\x00N\x00\x00\x00\x80QB\xC6\xFA\xB8^l\x9E)\xF5\xB2\xDC\x8F\xE07c\xEF\xDB\x17\xE1u)\xA9?\x02\xEB\xC1\xCCgV\x84V\xC3\xAB\x9Et\xC9n\x13&A\xC6uC\xFD'\xA5E\xD4\xC4\xBF\xCE2\x04^\xECr\xB6\xF7\xB3\xB6\x03\x97!m\xE5\xCE\xC62\xAA\xB6i]$\xADb\xA2\x985N\x15\x15]pMC\xD6:\x90\x1EL\x1E\"\xB7\xDE$\xF4\x97\xFE\x93cB\x03\xD4RB\xA7=\x1C\x18$\x8F\xFF\nc\x96\xE5ClI\xF3\x87\x95Mi-\xFE\xC6\x00\x00\x01\x14<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>Assistant Identifier</key>\n\t<string>13f93ee0-0ca9-4034-a755-f030c69f3675</string>\n</dict>\n</plist>\n\x00\x00\x00O\x01,\x80\x9B)\x16\xDAj\xDDm\x97I;\xE0\xF5+h\x01\xC1\x80<\x00\x00\x006\x06\x00\xBD\xA7\xB7\xE4\xA7\x8C6L\a\xCA\xDF\xCB[\x14KdQ\x16\x1F\xE2!MX\xBF_\xD2\x94\xBD\xBE\x16\xF3[,\x13E\xCC1\xBF\xDB\x04\x03?\xAF\xC6\t\xE0\xE8\x84W;\xD6=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
   "language"=>"en-US",
   "connectionType"=>"Wifi"}}
[Info - Forwarding object to Guzzoni] LoadAssistant
/Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in `encode': "\xEF\x8A" followed by "|" on UTF-8 (Encoding::InvalidByteSequenceError)
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in`charset_convert'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:48:in`to_binary'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:70:in `to_str'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:363:in`to_str'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:398:in `to_plist'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:150:in`inject_object_to_output_stream'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:90:in `process_compressed_data'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:58:in`receive_binary_data'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in`initialize'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`start_server'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in`initialize'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in `new'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in`<top (required)>'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/bin/siriproxy:23:in `load'
    from /Users/jamie/.rvm/gems/ruby-1.9.3-p385@SiriProxy/bin/siriproxy:23:in`<main>'
</code>

Thanks in advance!

**Comment by jamesabruce** [comment]
Much frustration later, fixed this using 

sudo gem install CFPropertyList -v 2.1.2

then copying the gem files from main ruby directory to the sirirproxy directory; and performed the config.yml edit described in issue 389 (sorry, dont know how to link to it)
